<a href="https://colab.research.google.com/github/abilashkannanv/AIML/blob/main/TrustCart_Phase1_Transaction_Risk_Prediction1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

### Task 1.1: Load datasets and identify records, features, and target variable

In [4]:
# Load transaction.csv
transactions_df = pd.read_csv('sample_data/transaction.csv')

# Load identity.csv
user_identity_df = pd.read_csv('sample_data/identity.csv')

print('Transactions DataFrame:')
display(transactions_df.head())
print('\nTransactions DataFrame Info:')
transactions_df.info()

print('\nUser Identity DataFrame:')
display(user_identity_df.head())
print('\nUser Identity DataFrame Info:')
user_identity_df.info()

Transactions DataFrame:

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Transactions DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 394 entries, TransactionID to V339
dtypes: float64(376), int64(4), object(14)
memory usage: 1.7+ GB

User Identity DataFrame:

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

User Identity DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144233 entries, 0 to 144232
Data columns (total 41 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionID  144233 non-null  int64
 1   id_01          144233 non-null  float64
 2   id_02          140872 non-null  float64
 3   id_03          66324 non-null   float64
 4   id_04          66324 non-null   float64
 5   id_05          136865 non-null  float64
 6   id_06          136865 non-null  float64
 7   id_07          5155 non-null    float64
 8   id_08          5155 non-null    float64
 9   id_09          74926 non-null   float64
 10  id_10          74926 non-null   float64
 11  id_11          140978 non-null  float64
 12  id_12          144233 non-null  object
 13  id_13          127320 non-null  float64
 14  id_14          80044 non-null   float64
 15  id_15          140985 non-null  object
 16  id_16          129340 non-null  object
 17  id_17          139369 non-null  float64
 18  id_18          45113 non-null   float64
 19  id_19          139318 non-null  float64
 20  id_20          139261 non-null  float64
 21  id_21          5159 non-null    float64
 22  id_22          5169 non-null    float64
 23  id_23          5169 non-null    object
 24  id_24          4747 non-null    float64
 25  id_25          5132 non-null    float64
 26  id_26          5163 non-null    float64
 27  id_27          5169 non-null    object
 28  id_28          140978 non-null  object
 29  id_29          140978 non-null  object
 30  id_30          77565 non-null   object
 31  id_31          140282 non-null  object
 32  id_32          77586 non-null   float64
 33  id_33          73289 non-null   object
 34  id_34          77805 non-null   object
 35  id_35          140985 non-null  object
 36  id_36          140985 non-null  object
 37  id_37          140985 non-null  object
 38  id_38          140985 non-null  object
 39  DeviceType     140810 non-null  object
 40  DeviceInfo     118666 non-null  object
dtypes: float64(23), int64(1), object(17)
memory usage: 45.1+ MB
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [6]:
# execute to load the dataframes correctly
transactions_df = pd.read_csv('sample_data/transaction.csv')
user_identity_df = pd.read_csv('sample_data/identity.csv')

print('Transactions DataFrame:')
display(transactions_df.head())
print('\nTransactions DataFrame Info:')
transactions_df.info()

print('\nUser Identity DataFrame:')
display(user_identity_df.head())
print('\nUser Identity DataFrame Info:')
user_identity_df.info()

target_variable = 'risk_flag'

if target_variable in transactions_df.columns:
    print(f"\nTarget variable '{target_variable}' found in transactions_df.")
    print(f"Number of records in transactions_df: {len(transactions_df)}")
    print(f"Number of features in transactions_df (including target): {len(transactions_df.columns)}")
elif target_variable in user_identity_df.columns:
    print(f"\nTarget variable '{target_variable}' found in user_identity_df.")
    print(f"Number of records in user_identity_df: {len(user_identity_df)}")
    print(f"Number of features in user_identity_df (including target): {len(user_identity_df.columns)}")
else:
    print(f"\nTarget variable '{target_variable}' not found in either DataFrame.")

Transactions DataFrame:

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Transactions DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 394 entries, TransactionID to V339
dtypes: float64(376), int64(4), object(14)
memory usage: 1.7+ GB

User Identity DataFrame:

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

User Identity DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144233 entries, 0 to 144232
Data columns (total 41 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionID  144233 non-null  int64
 1   id_01          144233 non-null  float64
 2   id_02          140872 non-null  float64
 3   id_03          66324 non-null   float64
 4   id_04          66324 non-null   float64
 5   id_05          136865 non-null  float64
 6   id_06          136865 non-null  float64
 7   id_07          5155 non-null    float64
 8   id_08          5155 non-null    float64
 9   id_09          74926 non-null   float64
 10  id_10          74926 non-null   float64
 11  id_11          140978 non-null  float64
 12  id_12          144233 non-null  object
 13  id_13          127320 non-null  float64
 14  id_14          80044 non-null   float64
 15  id_15          140985 non-null  object
 16  id_16          129340 non-null  object
 17  id_17          139369 non-null  float64
 18  id_18          45113 non-null   float64
 19  id_19          139318 non-null  float64
 20  id_20          139261 non-null  float64
 21  id_21          5159 non-null    float64
 22  id_22          5169 non-null    float64
 23  id_23          5169 non-null    object
 24  id_24          4747 non-null    float64
 25  id_25          5132 non-null    float64
 26  id_26          5163 non-null    float64
 27  id_27          5169 non-null    object
 28  id_28          140978 non-null  object
 29  id_29          140978 non-null  object
 30  id_30          77565 non-null   object
 31  id_31          140282 non-null  object
 32  id_32          77586 non-null   float64
 33  id_33          73289 non-null   object
 34  id_34          77805 non-null   object
 35  id_35          140985 non-null  object
 36  id_36          140985 non-null  object
 37  id_37          140985 non-null  object
 38  id_38          140985 non-null  object
 39  DeviceType     140810 non-null  object
 40  DeviceInfo     118666 non-null  object
dtypes: float64(23), int64(1), object(17)
memory usage: 45.1+ MB

Target variable 'risk_flag' not found in either DataFrame.

### Task 1.2: Identify common keys and decide join type

In [7]:
print('Common columns between transactions_df and user_identity_df:')
common_cols = set(transactions_df.columns) & set(user_identity_df.columns)
print(common_cols)

# Assuming 'User ID' or a similar column is the common key
# Let's inspect unique values in potential key columns if they exist

# Example of potential common keys (adjust based on actual common_cols)
if 'User ID' in common_cols:
    print(f"\nNumber of unique 'User ID' in transactions_df: {transactions_df['User ID'].nunique()}")
    print(f"Number of unique 'User ID' in user_identity_df: {user_identity_df['User ID'].nunique()}")

# Justify join type (assuming 'User ID' is the key)
# If we want to keep all transactions and add user identity where available, a left join is suitable.
# If we only want to keep records where both transaction and identity data exist, an inner join is suitable.
# If we want all user identities and corresponding transactions, a right join might be considered.
# If we want all records from both and fill missing with NaN, a full outer join.

# For this task, a left join from transactions_df to user_identity_df seems appropriate
# if the goal is to enrich transaction data with user identity information.
# However, without specific instructions on which table to prioritize or what analysis to perform, a general approach is to understand the overlap.

print("\nDecision for Join Type and Justification:")
print("Based on the likely goal of enriching transaction data with user details, a **left join** is typically appropriate. This ensures all transactions are retained, and user identity information is added where a match exists. If a 'User ID' from transactions_df does not have a corresponding entry in user_identity_df, the identity columns will have NaN values. If the goal was to analyze only users for whom we have both transaction and identity data, an **inner join** would be used.")
print("Let's assume 'User ID' is the common key for joining and proceed with a left join to ensure all transaction data is kept.")

# Perform a sample left join to demonstrate (optional, can be done in next step if user requests merge)
# merged_df = pd.merge(transactions_df, user_identity_df, on='User ID', how='left')
# display(merged_df.head())
# print(merged_df.info())

Common columns between transactions_df and user_identity_df:
{'TransactionID'}

Decision for Join Type and Justification:
Based on the likely goal of enriching transaction data with user details, a **left join** is typically appropriate. This ensures all transactions are retained, and user identity information is added where a match exists. If a 'User ID' from transactions_df does not have a corresponding entry in user_identity_df, the identity columns will have NaN values. If the goal was to analyze only users for whom we have both transaction and identity data, an **inner join** would be used.
Let's assume 'User ID' is the common key for joining and proceed with a left join to ensure all transaction data is kept.

In [8]:
# Perform the left join
merged_df = pd.merge(transactions_df, user_identity_df, on='TransactionID', how='left')

print('Merged DataFrame Head:')
display(merged_df.head())

print('\nMerged DataFrame Info:')
merged_df.info()

print(f"\nNumber of records in merged_df: {len(merged_df)}")
print(f"Number of features in merged_df: {len(merged_df.columns)}")

Merged DataFrame Head:

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

Merged DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 434 entries, TransactionID to DeviceInfo
dtypes: float64(399), int64(4), object(31)
memory usage: 1.9+ GB

Number of records in merged_df: 590540
Number of features in merged_df: 434

## Task 2.1 – Missing Value Analysis

In [12]:
# Calculate missing values and their percentages
missing_values = merged_df.isnull().sum()
missing_percentages = (merged_df.isnull().sum() / len(merged_df)) * 100

missing_info = pd.DataFrame({
    'Missing Count': missing_values,
    'Missing Percentage': missing_percentages
})

# Filter to show only columns with missing values and sort them
missing_info = missing_info[missing_info['Missing Count'] > 0].sort_values(by='Missing Percentage', ascending=False)

print("Columns with Missing Values and their Percentages:")
display(missing_info.head(20)) # Display top 20 columns with most missing values

# Categorize missingness (general observation)
print("\nCategorizing Missingness:")
high_missing = missing_info[missing_info['Missing Percentage'] > 70]
medium_missing = missing_info[(missing_info['Missing Percentage'] <= 70) & (missing_info['Missing Percentage'] > 30)]
low_missing = missing_info[missing_info['Missing Percentage'] <= 30]

if not high_missing.empty:
    print("\nHighly Missing Columns ( > 70% missing):")
    display(high_missing.head())
if not medium_missing.empty:
    print("\nModerately Missing Columns (30% - 70% missing):")
    display(medium_missing.head())
if not low_missing.empty:
    print("\nLow Missing Columns (<= 30% missing):")
    display(low_missing.head())

Columns with Missing Values and their Percentages:

       Missing Count  Missing Percentage
id_24         585793           99.196159
id_25         585408           99.130965
id_07         585385           99.127070
id_08         585385           99.127070
id_21         585381           99.126393
id_26         585377           99.125715
id_23         585371           99.124699
id_22         585371           99.124699
id_27         585371           99.124699
dist2         552913           93.628374
D7            551623           93.409930
id_18         545427           92.360721
D13           528588           89.509263
D14           528353           89.469469
D12           525823           89.041047
id_04         524216           88.768923
id_03         524216           88.768923
D6            517353           87.606767
id_33         517251           87.589494
id_10         515614           87.312290

Categorizing Missingness:

Highly Missing Columns ( > 70% missing):

       Missing Count  Missing Percentage
id_24         585793           99.196159
id_25         585408           99.130965
id_07         585385           99.127070
id_08         585385           99.127070
id_21         585381           99.126393

Moderately Missing Columns (30% - 70% missing):

       Missing Count  Missing Percentage
dist1         352271           59.652352
M5            350482           59.349409
M7            346265           58.635317
M8            346252           58.633115
M9            346252           58.633115

Low Missing Columns (<= 30% missing):

     Missing Count  Missing Percentage
M6          169360           28.678836
V51         168969           28.612626
V52         168969           28.612626
V36         168969           28.612626
V41         168969           28.612626

## Task 2.2 – Data Cleaning

### Handling Missing Values and Dropping/Retaining Columns

Given the high percentage of missing values in many columns, especially those from the `identity_df` that had no match in `transactions_df` (resulting in ~75-99% missing data), it's advisable to drop columns that have an excessively high percentage of missing values as they are unlikely to contribute meaningfully to the model and can introduce noise. We will set a threshold for dropping columns.

Let's start by dropping columns with more than, say, 80% missing values. We will then decide on a strategy for the remaining missing values.

In [13]:
# Define a threshold for dropping columns (e.g., 80% missing)
missing_threshold = 80

# Get columns to drop based on the threshold
columns_to_drop = missing_info[missing_info['Missing Percentage'] > missing_threshold].index.tolist()

print(f"Number of columns to drop (>{missing_threshold}% missing): {len(columns_to_drop)}")
print("Columns to be dropped:")
for col in columns_to_drop:
    print(f"- {col} ({missing_info.loc[col]['Missing Percentage']:.2f}% missing)")

# Drop the identified columns from merged_df
df_cleaned = merged_df.drop(columns=columns_to_drop)

print(f"\nShape of merged_df before dropping: {merged_df.shape}")
print(f"Shape of df_cleaned after dropping highly missing columns: {df_cleaned.shape}")

# Update missing_info for the cleaned DataFrame
missing_values_cleaned = df_cleaned.isnull().sum()
missing_percentages_cleaned = (df_cleaned.isnull().sum() / len(df_cleaned)) * 100

missing_info_cleaned = pd.DataFrame({
    'Missing Count': missing_values_cleaned,
    'Missing Percentage': missing_percentages_cleaned
})

missing_info_cleaned = missing_info_cleaned[missing_info_cleaned['Missing Count'] > 0].sort_values(by='Missing Percentage', ascending=False)

print("\nMissing values in df_cleaned after dropping high-missing columns:")
display(missing_info_cleaned.head(20))

# For the remaining missing values (moderately and low missing), we can consider imputation.
# Let's inspect the data types of columns with remaining missing values to choose an appropriate imputation strategy.

print("\nData types of columns with remaining missing values:")
display(df_cleaned[missing_info_cleaned.index].dtypes)

Number of columns to drop (>80% missing): 74
Columns to be dropped:
- id_24 (99.20% missing)
- id_25 (99.13% missing)
- id_07 (99.13% missing)
- id_08 (99.13% missing)
- id_21 (99.13% missing)
- id_26 (99.13% missing)
- id_23 (99.12% missing)
- id_22 (99.12% missing)
- id_27 (99.12% missing)
- dist2 (93.63% missing)
- D7 (93.41% missing)
- id_18 (92.36% missing)
- D13 (89.51% missing)
- D14 (89.47% missing)
- D12 (89.04% missing)
- id_04 (88.77% missing)
- id_03 (88.77% missing)
- D6 (87.61% missing)
- id_33 (87.59% missing)
- id_10 (87.31% missing)
- D8 (87.31% missing)
- id_09 (87.31% missing)
- D9 (87.31% missing)
- id_30 (86.87% missing)
- id_32 (86.86% missing)
- id_34 (86.82% missing)
- id_14 (86.45% missing)
- V146 (86.12% missing)
- V147 (86.12% missing)
- V148 (86.12% missing)
- V158 (86.12% missing)
- V157 (86.12% missing)
- V153 (86.12% missing)
- V162 (86.12% missing)
- V161 (86.12% missing)
- V139 (86.12% missing)
- V138 (86.12% missing)
- V141 (86.12% missing)
- V140 (86.12% missing)
- V163 (86.12% missing)
- V155 (86.12% missing)
- V156 (86.12% missing)
- V142 (86.12% missing)
- V154 (86.12% missing)
- V149 (86.12% missing)
- V143 (86.12% missing)
- V160 (86.12% missing)
- V151 (86.12% missing)
- V159 (86.12% missing)
- V165 (86.12% missing)
- V166 (86.12% missing)
- V152 (86.12% missing)
- V164 (86.12% missing)
- V144 (86.12% missing)
- V145 (86.12% missing)
- V150 (86.12% missing)
- V338 (86.05% missing)
- V339 (86.05% missing)
- V337 (86.05% missing)
- V336 (86.05% missing)
- V329 (86.05% missing)
- V330 (86.05% missing)
- V331 (86.05% missing)
- V332 (86.05% missing)
- V333 (86.05% missing)
- V334 (86.05% missing)
- V335 (86.05% missing)
- V324 (86.05% missing)
- V325 (86.05% missing)
- V326 (86.05% missing)
- V327 (86.05% missing)
- V328 (86.05% missing)
- V322 (86.05% missing)
- V323 (86.05% missing)

Shape of merged_df before dropping: (590540, 434)
Shape of df_cleaned after dropping highly missing columns: (590540, 360)

Missing values in df_cleaned after dropping high-missing columns:

            Missing Count  Missing Percentage
DeviceInfo         471874           79.905510
id_13              463220           78.440072
id_16              461200           78.098012
V278               460110           77.913435
V277               460110           77.913435
V274               460110           77.913435
V273               460110           77.913435
V276               460110           77.913435
V275               460110           77.913435
V267               460110           77.913435
V266               460110           77.913435
V265               460110           77.913435
V264               460110           77.913435
V263               460110           77.913435
V262               460110           77.913435
V261               460110           77.913435
V260               460110           77.913435
V258               460110           77.913435
V257               460110           77.913435
V254               460110           77.913435

Data types of columns with remaining missing values:

DeviceInfo     object
id_13         float64
id_16          object
V278          float64
V277          float64
               ...
V311          float64
V312          float64
V321          float64
V319          float64
V320          float64
Length: 340, dtype: object

### Handle Remaining Missing Values (Imputation)

In [14]:
# Separate numerical and categorical columns for imputation

numerical_cols_with_missing = missing_info_cleaned[df_cleaned[missing_info_cleaned.index].dtypes != 'object'].index.tolist()
categorical_cols_with_missing = missing_info_cleaned[df_cleaned[missing_info_cleaned.index].dtypes == 'object'].index.tolist()

print(f"Number of numerical columns with remaining missing values: {len(numerical_cols_with_missing)}")
print(f"Number of categorical columns with remaining missing values: {len(categorical_cols_with_missing)}")

# Impute numerical columns with the median
print("\nImputing numerical columns with median...")
for col in numerical_cols_with_missing:
    if col in df_cleaned.columns:
        median_val = df_cleaned[col].median()
        df_cleaned[col].fillna(median_val, inplace=True)
        # print(f"  Imputed '{col}' with median: {median_val}")

# Impute categorical columns with the mode
print("\nImputing categorical columns with mode...")
for col in categorical_cols_with_missing:
    if col in df_cleaned.columns:
        mode_val = df_cleaned[col].mode()[0] # .mode() can return multiple if frequencies are tied
        df_cleaned[col].fillna(mode_val, inplace=True)
        # print(f"  Imputed '{col}' with mode: {mode_val}")

print("\nMissing value imputation complete. Verifying...")

# Verify no more missing values in df_cleaned
missing_after_imputation = df_cleaned.isnull().sum()
missing_after_imputation = missing_after_imputation[missing_after_imputation > 0]

if missing_after_imputation.empty:
    print("All missing values have been handled.")
else:
    print("Remaining missing values (should be none if all categories handled):")
    display(missing_after_imputation)

print(f"\nFinal shape of df_cleaned: {df_cleaned.shape}")
display(df_cleaned.head())

Number of numerical columns with remaining missing values: 315
Number of categorical columns with remaining missing values: 25

Imputing numerical columns with median...

/tmp/ipykernel_14805/3810781248.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(median_val, inplace=True)

Imputing categorical columns with mode...

/tmp/ipykernel_14805/3810781248.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(mode_val, inplace=True)

Missing value imputation complete. Verifying...
All missing values have been handled.

Final shape of df_cleaned: (590540, 360)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,361.0,150.0,discover,142.0,...,472.0,Found,Found,chrome 63.0,T,F,T,F,desktop,Windows
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,472.0,Found,Found,chrome 63.0,T,F,T,F,desktop,Windows
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,472.0,Found,Found,chrome 63.0,T,F,T,F,desktop,Windows
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,472.0,Found,Found,chrome 63.0,T,F,T,F,desktop,Windows
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,144.0,New,NotFound,samsung browser 6.2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

#### Transactions DataFrame Overview

In [9]:
print('Transactions DataFrame:')
display(transactions_df.head())
print('\nTransactions DataFrame Info:')
transactions_df.info()

Transactions DataFrame:

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Transactions DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 394 entries, TransactionID to V339
dtypes: float64(376), int64(4), object(14)
memory usage: 1.7+ GB

#### User Identity DataFrame Overview

In [10]:
print('\nUser Identity DataFrame:')
display(user_identity_df.head())
print('\nUser Identity DataFrame Info:')
user_identity_df.info()

User Identity DataFrame:

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

User Identity DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144233 entries, 0 to 144232
Data columns (total 41 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionID  144233 non-null  int64
 1   id_01          144233 non-null  float64
 2   id_02          140872 non-null  float64
 3   id_03          66324 non-null   float64
 4   id_04          66324 non-null   float64
 5   id_05          136865 non-null  float64
 6   id_06          136865 non-null  float64
 7   id_07          5155 non-null    float64
 8   id_08          5155 non-null    float64
 9   id_09          74926 non-null   float64
 10  id_10          74926 non-null   float64
 11  id_11          140978 non-null  float64
 12  id_12          144233 non-null  object
 13  id_13          127320 non-null  float64
 14  id_14          80044 non-null   float64
 15  id_15          140985 non-null  object
 16  id_16          129340 non-null  object
 17  id_17          139369 non-null  float64
 18  id_18          45113 non-null   float64
 19  id_19          139318 non-null  float64
 20  id_20          139261 non-null  float64
 21  id_21          5159 non-null    float64
 22  id_22          5169 non-null    float64
 23  id_23          5169 non-null    object
 24  id_24          4747 non-null    float64
 25  id_25          5132 non-null    float64
 26  id_26          5163 non-null    float64
 27  id_27          5169 non-null    object
 28  id_28          140978 non-null  object
 29  id_29          140978 non-null  object
 30  id_30          77565 non-null   object
 31  id_31          140282 non-null  object
 32  id_32          77586 non-null   float64
 33  id_33          73289 non-null   object
 34  id_34          77805 non-null   object
 35  id_35          140985 non-null  object
 36  id_36          140985 non-null  object
 37  id_37          140985 non-null  object
 38  id_38          140985 non-null  object
 39  DeviceType     140810 non-null  object
 40  DeviceInfo     118666 non-null  object
dtypes: float64(23), int64(1), object(17)
memory usage: 45.1+ MB

#### Identify Target Variable (risk_flag)

Let's check if 'risk_flag' is present in either DataFrame and identify the number of records and features.

In [11]:
target_variable = 'risk_flag'

if target_variable in transactions_df.columns:
    print(f"Target variable '{target_variable}' found in transactions_df.")
    print(f"Number of records in transactions_df: {len(transactions_df)}")
    print(f"Number of features in transactions_df: {len(transactions_df.columns)}")
elif target_variable in user_identity_df.columns:
    print(f"Target variable '{target_variable}' found in user_identity_df.")
    print(f"Number of records in user_identity_df: {len(user_identity_df)}")
    print(f"Number of features in user_identity_df: {len(user_identity_df.columns)}")
else:
    print(f"Target variable '{target_variable}' not found in either DataFrame.")

Target variable 'risk_flag' not found in either DataFrame.